-- phpMyAdmin SQL Dump
-- version 4.6.4
-- https://www.phpmyadmin.net/
--
-- Client :  127.0.0.1
-- Généré le :  Sam 21 Janvier 2017 à 14:59
-- Version du serveur :  5.7.14
-- Version de PHP :  5.6.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données :  `db_ntic`
--
CREATE DATABASE IF NOT EXISTS `db_ntic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `db_ntic`;

-- --------------------------------------------------------

--
-- Structure de la table `bouton`
--

CREATE TABLE `bouton` (
  `id_bouton` int(11) NOT NULL,
  `id_page` int(11) NOT NULL,
  `go_to_page` int(11) NOT NULL,
  `texte` varchar(500) CHARACTER SET latin1 NOT NULL,
  `flag` varchar(100) DEFAULT NULL,
  `score` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Contenu de la table `bouton`
--

INSERT INTO `bouton` (`id_bouton`, `id_page`, `go_to_page`, `texte`, `flag`, `score`) VALUES
(36, 33, 2, 'Continuer', NULL, 0),
(37, 34, 3, 'Continuer', NULL, 0),
(38, 35, 4, 'Vous demandez un rendez-vous Ã  la mairie', NULL, 2),
(39, 35, 5, 'Vous insistez auprÃ¨s d\'Emma', NULL, 1),
(40, 35, 6, 'Vous laissez Emma le faire quand elle le voudra', NULL, -2),
(41, 36, 7, 'Vous prenez les devants et prÃ©parez les dossiers', NULL, 2),
(42, 36, 8, 'Vous dites Ã  Emma de penser Ã  faire son dossier', NULL, -2),
(43, 37, 7, 'Vous prenez les devants et prÃ©parez les dossiers', NULL, 2),
(44, 37, 8, 'Vous dites Ã  Emma de penser Ã  faire son dossier', NULL, -2),
(45, 38, 7, 'Vous prenez les devants et prÃ©parez les dossiers', NULL, 2),
(46, 38, 8, 'Vous dites Ã  Emma de penser Ã  faire son dossier', NULL, -2),
(47, 39, 9, 'Passer Ã  la suite', 'formOK', 0),
(48, 40, 9, 'Passer Ã  la suite', 'formNOK', 0),
(49, 41, 10, 'Vous essayez de nÃ©gocier', NULL, -2),
(50, 41, 11, 'Vous acceptez de l\'accompagner', NULL, 0),
(51, 42, 12, 'Vous essayez de la rassurer', NULL, 1),
(52, 42, 13, 'Vous lui demandez ce qui lui arrive', NULL, 2),
(53, 42, 14, 'Vous la motivez Ã  avancer', NULL, -3),
(54, 43, 12, 'Vous essayez de la rassurer', NULL, 1),
(55, 43, 13, 'Vous lui demandez ce qui lui arrive', NULL, 2),
(56, 43, 14, 'Vous la motivez Ã  avancer', NULL, -3),
(57, 44, 15, 'Suite', NULL, 0),
(58, 45, 15, 'Suite', NULL, 0),
(59, 46, 15, 'Suite', NULL, 0),
(60, 47, 16, 'Vous allez la chercher dehors', NULL, 2),
(61, 47, 17, 'Vous lui envoyez un texto', NULL, 1),
(62, 47, 18, 'Vous attendez qu\'elle revienne dans la file', NULL, -2),
(63, 48, 19, 'Suite', '', 0),
(64, 49, 19, 'Suite', '', 0),
(65, 50, 19, 'Suite', '', 0),
(66, 51, 21, 'Expliquer Ã  sa place', '', 2),
(67, 51, 22, 'Expliquer que Emma est atteinte de PTSD', '', 1),
(68, 51, 23, 'Demander Ã  Emma de se concentrer', '', -3),
(69, 52, 21, 'Expliquer Ã  sa place', '', 2),
(70, 52, 22, 'Expliquer que Emma est atteinte de PTSD', '', 1),
(71, 52, 23, 'Demander Ã  Emma de se concentrer', '', -3),
(72, 53, 0, 'Recommencer ?', NULL, 0),
(73, 54, 0, 'Recommencer ?', '', 0),
(74, 55, 0, 'Recommencer ?', NULL, 0),
(96, 67, 1, 'OK', '', 0),
(97, 68, 24, 'Suite', '', 0),
(98, 69, 24, 'Suite', '', 0),
(99, 70, 24, 'Suite', '', 0),
(101, 72, 2, 'Continuer', '', 0),
(102, 73, 3, 'Continuer', '', 0),
(103, 74, 4, 'Vous rappelez Ã  Marco qu\'il doit regarder les horaires de bus', NULL, 1),
(104, 74, 5, 'Vous vÃ©rifiez vous-mÃªme les horaires de bus', NULL, 2),
(105, 74, 6, 'Vous faites confiance Ã  Marco', NULL, -2),
(106, 75, 7, 'Passer Ã  la suite', '', 0),
(107, 76, 7, 'Passer Ã  la suite', '', 0),
(108, 77, 7, 'Passer Ã  la suite', '', 0),
(109, 78, 8, 'Vous tentez de le rassurer', '', 1),
(110, 78, 9, 'Vous ignorez le comportement de Marco', '', -2),
(111, 78, 10, 'Vous dites Ã  Marco de garder son calme', '', -1),
(112, 79, 11, 'Passer Ã  la suite', '', 0),
(113, 80, 11, 'Passer Ã  la suite', '', 0),
(114, 81, 11, 'Passer Ã  la suite', '', 0),
(115, 82, 12, 'Vous invitez Marco Ã  se joindre Ã  une conversation', NULL, 2),
(116, 82, 13, 'Vous le laissez', NULL, -2),
(117, 83, 14, 'Passer Ã  la suite', '', 0),
(118, 84, 14, 'Passer Ã  la suite', '', 0),
(119, 85, 15, 'Vous l\'aidez Ã  rÃ©aliser l\'exercice', '', 2),
(120, 85, 16, 'Vous ignorez Marco', '', -2),
(121, 85, 17, 'Vous l\'encouragez Ã  faire l\'exercice', '', 1),
(122, 86, 18, 'Suite', '', 0),
(123, 87, 18, 'Suite', '', 0),
(124, 88, 18, 'Suite', '', 0),
(125, 89, 19, 'Vous l\'interpellez pour qu\'il soit plus rÃ©actif', '', 2),
(126, 89, 20, 'Vous continuez l\'improvisation en essayant d\'inclure Marco', '', -2),
(127, 89, 21, 'Vous continuez l\'improvisation en ignorant Marco', '', -1),
(128, 90, 22, 'Suite', '', 0),
(129, 91, 22, 'Suite', '', 0),
(130, 92, 22, 'Suite', '', 0),
(131, 93, 23, 'Lui soufflez la rÃ©ponse', '', 1),
(132, 93, 24, 'ExagÃ©rez pour l\'aider', '', 2),
(133, 93, 25, 'Continuer l\'exercice sans exagÃ©rer', '', -2),
(134, 94, 26, 'Suite', '', 0),
(135, 95, 26, 'Suite', '', 0),
(136, 96, 26, 'Suite', '', 0),
(137, 97, 27, 'Attendre que la crise de Marco passe', NULL, -2),
(138, 97, 28, 'Lui dire que tout va bien et qu\'il est en sÃ©curitÃ©', NULL, 2),
(139, 98, 29, 'Suite', '', 0),
(140, 99, 29, 'Suite', '', 0),
(141, 100, 1, 'Recommencer ?', '', 0),
(142, 101, 1, 'Recommencer ?', '', 0),
(143, 102, 1, 'Recommencer ?', '', 0);

-- --------------------------------------------------------

--
-- Structure de la table `page`
--

CREATE TABLE `page` (
  `id_page` int(11) NOT NULL,
  `id_scenario` int(11) NOT NULL,
  `numero` int(11) NOT NULL,
  `texte` varchar(5000) NOT NULL,
  `image` varchar(500) DEFAULT NULL,
  `titre` varchar(100) CHARACTER SET utf8 NOT NULL,
  `requis` varchar(100) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `page`
--

INSERT INTO `page` (`id_page`, `id_scenario`, `numero`, `texte`, `image`, `titre`, `requis`) VALUES
(33, 12, 1, 'Il y a quelques mois, Emma, militaire de profession, est rentrÃ©e dâ€™une mission sur le terrain. Malheureusement, alors quâ€™elle Ã©tait de garde Ã  lâ€™ambassade franÃ§aise en Lybie, une explosion a eu lieu, entraÃ®nant la mort de plusieurs victimes. Depuis son retour en France, elle vit chez son compagnon Mohammed. Depuis, Emma est en proie Ã  des crises dâ€™angoisse et des insomnies causÃ©s par des cauchemars. Elle semble plus distante, irritable et sursaute au moindre bruit inattendu. AprÃ¨s consultation dâ€™un psychiatre, Emma a Ã©tÃ© diagnostiquÃ©e comme ayant un syndrome de stress post-traumatique (ou SPT). ', 'ressources/a1dd4d84a1ccddad744012d3bf77fc0c.PNG', 'Introduction', NULL),
(34, 12, 2, 'Vous incarnez Mohammed, le compagnon dâ€™Emma. Au vu de son diagnostic, votre rÃ´le est dÃ©sormais de lui apporter un soutien quotidien pour lâ€™aider Ã  vivre avec sa maladie.', 'ressources/490105a584724833a64bbc72db535740.PNG', 'Etape 1', NULL),
(35, 12, 3, '<p><strong>Pour vous changer les id&eacute;es, vous d&eacute;cidez de partir au Br&eacute;sil. Pour cela, il va falloir qu&rsquo;Emma renouvelle son passeport &agrave; la mairie. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>N&eacute;anmoins, malgr&eacute; une semaine que vous r&eacute;p&eacute;tez &agrave; Emma de d&eacute;buter les d&eacute;marches administrative, elle n&rsquo;a pour l&rsquo;instant rien fait. La date du d&eacute;part approche, et il va bien falloir faire ces d&eacute;marches. Que faites-vous ?</p>\r\n', 'ressources/4f5e7bf1dee8471e958b42f0679b7cc4.PNG', 'Etape 2', NULL),
(36, 12, 4, '<p><strong>Vous vous chargez d&rsquo;appeler la mairie pour pr&eacute;parer un rendez-vous et savoir quelles pi&egrave;ces amener. Pendant l&rsquo;appel, vous pouvez clairement voir l&rsquo;irritation d&rsquo;Emma devant votre initiative. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes en situation de SPT peuvent &ecirc;tre irritables ou r&eacute;agir de mani&egrave;re impr&eacute;vue &agrave; cause d&rsquo;une alt&eacute;ration de l&rsquo;humeur et / ou de la rationalit&eacute;. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Malgr&eacute; la r&eacute;action d&rsquo;Emma, vous avez planifi&eacute; un rendez-vous avec la mairie, qui n&eacute;cessitera des pi&egrave;ces pour constituer un dossier. Au vu de ce qui s&rsquo;est pass&eacute; pour prendre le rendez-vous, vous h&eacute;sitez &agrave; laisser Emma s&rsquo;en charger seule. Que faites-vous ?</p>\r\n', 'ressources/5a9bffbb27f05b17bc0326ae1797f657.PNG', 'Etape 2 - a', NULL),
(37, 12, 5, '<p><strong>Vous dites &agrave; Emma qu&rsquo;il faut le faire d&egrave;s que possible. Elle s&rsquo;&eacute;nerve soudainement contre vous, arguant que &ccedil;a ne vous regarde pas et que &ccedil;a n&rsquo;en vaut pas la peine de toute fa&ccedil;on. Cela vous &eacute;tonne, elle voulait ce voyage ! Vous appelez alors la mairie malgr&eacute; ses protestations et obtenez un rendez-vous. </strong></p>\r\n\r\n<p><strong>Les personnes en situation de SPT peuvent &ecirc;tre irritables ou r&eacute;agir de mani&egrave;re impr&eacute;vue &agrave; cause d&rsquo;une alt&eacute;ration de l&rsquo;humeur et / ou de la rationalit&eacute;. </strong></p>\r\n\r\n<p>Malgr&eacute; la r&eacute;action d&rsquo;Emma, vous avez planifi&eacute; un rendez-vous avec la mairie, qui n&eacute;cessitera des pi&egrave;ces pour constituer un dossier. Au vu de ce qui s&rsquo;est pass&eacute; pour prendre le rendez-vous, vous h&eacute;sitez &agrave; laisser Emma s&rsquo;en charger seule. Que faites-vous ?</p>\r\n', 'ressources/09b16b2bb3465c7add737767bca91f61.PNG', 'Etape 2 - b', NULL),
(38, 12, 6, '<p><strong>Le temps passe et vous n&rsquo;avez aucune nouvelle du rendez-vous&hellip; A chaque fois que vous en parlez &agrave; Emma, elle dit qu&rsquo;elle a oubli&eacute;. Au bout d&rsquo;un moment, vous d&eacute;cidez de prendre les choses en main en composant vous m&ecirc;me le num&eacute;ro pour donner le t&eacute;l&eacute;phone &agrave; Emma. Celle-ci vous lance un regard noir pendant qu&rsquo;elle prend le rendez-vous, en rudoyant sensiblement son interlocuteur. </strong></p>\r\n\r\n<p><strong>Les personnes en situation de SPT peuvent &ecirc;tre irritables ou r&eacute;agir de mani&egrave;re impr&eacute;vue &agrave; cause d&rsquo;une alt&eacute;ration de l&rsquo;humeur et / ou de la rationalit&eacute;. </strong></p>\r\n\r\n<p>Malgr&eacute; la r&eacute;action d&rsquo;Emma, vous avez planifi&eacute; un rendez-vous avec la mairie, qui n&eacute;cessitera des pi&egrave;ces pour constituer un dossier. Au vu de ce qui s&rsquo;est pass&eacute; pour prendre le rendez-vous, vous h&eacute;sitez &agrave; laisser Emma s&rsquo;en charger seule. Que faites-vous ?</p>\r\n', 'ressources/19d6e96c75bd6c9a726e7164bd8a7afd.PNG', 'Etape 2 - c', NULL),
(39, 12, 7, '<p><strong>D&eacute;j&agrave; que cela a &eacute;t&eacute; compliqu&eacute; d&rsquo;appeler la mairie&hellip; Vous ne prenez pas de risque et vous cherchez les pi&egrave;ces n&eacute;cessaires au dossier. Au d&eacute;part vex&eacute;e, Emma finit par compl&eacute;ter le dossier avec vous. </strong></p>\r\n\r\n<p><strong>Les personnes atteintes de SPT ont des difficult&eacute;s &agrave; s&rsquo;impliquer dans des activit&eacute;s importantes. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Le dossier est pr&ecirc;t, et c&rsquo;est le jour pour Emma d&rsquo;aller &agrave; la mairie.</p>\r\n', 'ressources/7bb9d99df8f6959431f1cd69e47bf813.PNG', 'Etape 3 - a', NULL),
(40, 12, 8, '<p><strong>Emma vous r&eacute;pond qu&rsquo;elle pense pouvoir s&rsquo;en sortir toute seule. Vous doutez un peu &agrave; cause de ce qui s&rsquo;est pass&eacute; pour le rendez-vous, mais vous voyez bien que &ccedil;a lui tient &agrave; coeur. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Le dossier est pr&ecirc;t, et c&rsquo;est le jour pour Emma d&rsquo;aller &agrave; la mairie.</p>\r\n', 'ressources/d2759e5f806feb79b9705aaf06e15dbd.PNG', 'Etape 3 - b', NULL),
(41, 12, 9, '<p><strong>Le matin au petit-d&eacute;jeuner, Emma vous demande si vous voulez bien l&rsquo;accompagner &agrave; la mairie. Vous voyez qu&rsquo;elle ne semble pas rassur&eacute;e, comme souvent quand il s&rsquo;agit d&rsquo;une sortie. </strong></p>\r\n\r\n<p><strong>Les personnes atteintes de SPT tentent d&rsquo;&eacute;viter au maximum les lieux ou les situations qui peuvent ressembler &agrave; l&#39;&eacute;v&eacute;nement traumatisant. Elles peuvent faire beaucoup d&rsquo;efforts pour se rassurer et se prot&eacute;ger. De plus, elles peuvent ressentir de nombreuses &eacute;motions n&eacute;gatives et peuvent chercher le soutien de leur proche. </strong></p>\r\n\r\n<p>Dommage pour vous, vous aviez pr&eacute;vu de ne rien faire de la matin&eacute;e. Emma compte beaucoup pour vous, mais vous aimeriez pouvoir vous reposer apr&egrave;s une semaine tr&egrave;s fatigante. Que d&eacute;cidez-vous ?</p>\r\n', 'ressources/020dcaa2a7060de5c1b3908068327e0c.PNG', 'Etape 4', NULL),
(42, 12, 10, '<p><strong>Vous essayez d&rsquo;expliquer &agrave; Emma que vous &ecirc;tes fatigu&eacute; mais avant d&rsquo;aller plus loin, elle vous interrompt, d&rsquo;une voix tremblante. Elle vous dit qu&rsquo;elle a vraiment besoin de vous pour aller &agrave; la mairie, car elle ne sent pas tr&egrave;s bien et qu&rsquo;elle a peur d&rsquo;oublier des informations. Vous voyez clairement qu&rsquo;il y a un vrai sentiment de peur derri&egrave;re &ccedil;a, et vous d&eacute;cidez de l&rsquo;accompagner pour la rassurer. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Sur le chemin pour la mairie, vous bavardez tranquillement lorsque soudainement, Emma se fige. Vous regardez alors devant elle et vous ne voyez que la mairie. Devant l&rsquo;aspect officiel du b&acirc;timent et le drapeau fran&ccedil;ais, vous comprenez &agrave; alors ce qui arrive &agrave; Emma.</p>\r\n', 'ressources/51921a40f939302644d2ccae80e73a81.PNG', 'Etape 4 - a', NULL),
(43, 12, 11, '<p><strong>Emma semble rassurer que vous ayez d&eacute;cid&eacute; de l&rsquo;accompagner. Vous partez donc avec Emma en direction de la mairie apr&egrave;s avoir finis votre petit d&eacute;jeuner. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Sur le chemin pour la mairie, vous bavardez tranquillement lorsque soudainement, Emma se fige. Vous regardez alors devant elle et vous ne voyez que la mairie. Devant l&rsquo;aspect officiel du b&acirc;timent et le drapeau fran&ccedil;ais, vous comprenez &agrave; alors ce qui arrive &agrave; Emma.</p>\r\n', 'ressources/43ae0ce7dbfd7a4691d946e8da407ead.PNG', 'Etape 4 - b', NULL),
(44, 12, 12, '<p><strong>Vous la serrez contre vous pour la rassurer en disant des paroles de r&eacute;confort. Vous voyez qu&rsquo;elle tremble et qu&rsquo;elle respire difficilement et vous esp&eacute;rez l&rsquo;apaiser. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Le SPT peut causer des hallucinations ou des r&ecirc;ves. Les personnes atteintes peuvent alors revivre la situation traumatisante ce qui est tr&egrave;s angoissant pour eux. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au bout d&rsquo;un moment vous la sentez se calmer et reprendre une respiration plus repos&eacute;e. Elle ne vous dit rien, mais reprend le chemin vers la mairie.</p>\r\n', 'ressources/94d28774eef9525d4980ce57adb800ce.PNG', 'Etape 5 - a', NULL),
(45, 12, 13, '<p><strong>Apr&egrave;s un long silence, elle reprend ses esprits. Puis elle vous dit d&rsquo;une voix faible qu&rsquo;en voyant la mairie, elle a revu l&rsquo;attaque de l&rsquo;ambassade pendant sa mission. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Le SPT peut causer des hallucinations ou des r&ecirc;ves. Les personnes atteintes peuvent alors revivre la situation traumatisante ce qui est tr&egrave;s angoissant pour eux. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>C&rsquo;&eacute;tait donc ce que vous pensiez, mais vous ne vous doutiez que &ccedil;a aurait pu arriver pour un moment aussi banal. Pourtant, c&rsquo;est le cas, et il faut quand m&ecirc;me bien aller &agrave; la mairie m&ecirc;me s&rsquo;il faut m&eacute;nager Emma, qui a l&rsquo;air &eacute;branl&eacute;e.</p>\r\n', 'ressources/ea50b2a0af67b3d9b6523471f5a4694f.PNG', 'Etape 5 - b', NULL),
(46, 12, 14, '<p><strong>Vous lui expliquez pos&eacute;ment qu&rsquo;elle est en s&eacute;curit&eacute; et qu&rsquo;il n&rsquo;y a pas de raison d&rsquo;avoir peur car elle est loin de tout &ccedil;a. Elle vous &eacute;coute sans rien dire dans un premier temps.</strong></p>\r\n\r\n<p><strong>Le SPT peut causer des hallucinations ou des r&ecirc;ves. Les personnes atteintes peuvent alors revivre la situation traumatisante ce qui est tr&egrave;s angoissant pour eux. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Elle vous suit sans r&eacute;agir, en se laissant faire.</p>\r\n', 'ressources/e81c1db447eab0ff19b15ecbf0103689.PNG', 'Etape 5 - c', NULL),
(47, 12, 15, '<p><strong>Aller &agrave; la mairie aujourd&rsquo;hui n&rsquo;&eacute;tait peut-&ecirc;tre pas la meilleure id&eacute;e&hellip; Il semblerait que tout votre quartier ait d&eacute;cid&eacute; d&rsquo;aller &agrave; la mairie aujourd&rsquo;hui. Vous allez devoir patienter dans la file d&rsquo;attente. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au bout d&rsquo;une dizaine de minutes, Emma vous dit qu&rsquo;elle en a marre et va prendre l&rsquo;air un moment. Vous auriez bien aim&eacute; pouvoir l&rsquo;accompagner, mais l&rsquo;un de vous doit rester, et elle avait l&rsquo;air d&rsquo;en avoir besoin. Alors que la file avance, Emma ne semble pas revenir. Vous avez pourtant besoin d&rsquo;elle pour aller au rendez-vous.</p>\r\n', 'ressources/9a9febcffc5c60d110bd2bc0afb08f61.PNG', 'Etape 6', NULL),
(48, 12, 16, '<p><strong>Vous allez la voir dehors pour lui demander si tout va bien. Elle vous r&eacute;pond qu&rsquo;au vu de la situation, elle avait besoin d&rsquo;air mais que &ccedil;a va mieux. N&eacute;anmoins, le temps que vous discutiez, vous avez perdu votre place dans la file d&rsquo;attente et vous allez devoir recommencer. Apr&egrave;s ce qui vous semble &ecirc;tre une heure, vous arrivez au guichet. </strong></p>\r\n\r\n<p><strong>Les personnes atteintes de SPT ont un tendance &agrave; &ecirc;tre sensible au monde qui les entoure, on appelle cela l&rsquo;hypervigilance. Une foule ou une file d&rsquo;attente peut alors repr&eacute;senter une situation de stress importante. </strong></p>\r\n\r\n<p>Vous et Emma d&eacute;taillez alors les raisons de votre venue. La guicheti&egrave;re vous redirige alors vers le bureau o&ugrave; il vous faut aller. L&agrave;, une fonctionnaire vous accueille et vous demande les pi&egrave;ces n&eacute;cessaires.</p>\r\n', 'ressources/eab61e25faa9aa309f3b770a50e23002.PNG', 'Etape 6 - a', ''),
(49, 12, 17, '<p><strong>&ldquo;Ca va ? Tu es o&ugrave; ?&rdquo;. 2 minutes apr&egrave;s votre texto, vous voyez Emma revenir. Elle n&rsquo;a pas l&rsquo;air d&rsquo;&ecirc;tre au mieux de sa forme, mais cela va un peu mieux. Surtout, il &eacute;tait temps car c&rsquo;est bient&ocirc;t &agrave; vous d&rsquo;aller au guichet. </strong></p>\r\n\r\n<p><strong>Les personnes atteintes de SPT ont un tendance &agrave; &ecirc;tre sensible au monde qui les entoure, on appelle cela l&rsquo;hypervigilance. Une foule ou une file d&rsquo;attente peut alors repr&eacute;senter une situation de stress importante. </strong></p>\r\n\r\n<p>Vous et Emma d&eacute;taillez alors les raisons de votre venue. La guicheti&egrave;re vous redirige alors vers le bureau o&ugrave; il vous faut aller. L&agrave;, une fonctionnaire vous accueille et vous demande les pi&egrave;ces n&eacute;cessaires.</p>\r\n', 'ressources/f131ac928dc781a040144b394b985624.PNG', 'Etape 6 - b', ''),
(50, 12, 18, '<p><strong>Le temps passe, et Emma ne montre pas de signe. Lorsque c&rsquo;est votre tour, vous expliquez &agrave; la guicheti&egrave;re que c&rsquo;est pour vous et votre partenaire, qui va bient&ocirc;t arriver. Apr&egrave;s deux longues minutes o&ugrave; vous essayez de convaincre la guicheti&egrave;re qu&rsquo;elle va arriver d&rsquo;une minute &agrave; l&rsquo;autre, Emma revient enfin, plus sereine. </strong></p>\r\n\r\n<p><strong>Les personnes atteintes de SPT ont un tendance &agrave; &ecirc;tre sensible au monde qui les entoure, on appelle cela l&rsquo;hypervigilance. Une foule ou une file d&rsquo;attente peut alors repr&eacute;senter une situation de stress importante. </strong></p>\r\n\r\n<p>Vous et Emma d&eacute;taillez alors les raisons de votre venue. La guicheti&egrave;re vous redirige alors vers le bureau o&ugrave; il vous faut aller. L&agrave;, une fonctionnaire vous accueille et vous demande les pi&egrave;ces n&eacute;cessaires.</p>\r\n', 'ressources/203b09a1b65ec8733de4dbaa14dc3012.PNG', 'Etape 6 - c', ''),
(51, 12, 19, '<p><strong>Vous prenez les pi&egrave;ces que Emma et vous avez pr&eacute;par&eacute;. Tout y est, et vous pouvez commencer &agrave; remplir les papiers n&eacute;cessaires. La fonctionnaire vous pose des questions pour pouvoir faire vos passeports. </strong></p>\r\n\r\n<p><strong>Il est possible que les personnes atteintes de SPT d&eacute;veloppent des probl&egrave;mes de concentration. Il devient alors plus difficile pour eux de r&eacute;aliser une t&acirc;che du d&eacute;but &agrave; la fin. </strong></p>\r\n\r\n<p>Au bout de 5 minutes de questions, Emma commence &agrave; montrer des signes d&rsquo;impatience et de d&eacute;concentration. Elle met plus de temps &agrave; r&eacute;pondre, et s&rsquo;y reprend &agrave; plusieurs fois pour expliquer sa situation. La fonctionnaire semble perdre patience. Vous d&eacute;cidez alors de...</p>\r\n', 'ressources/3b3182761df0dd32af96c92c614692df.PNG', 'Etape 7 - a', 'formOK'),
(52, 12, 19, '<p><strong>Vous prenez les pi&egrave;ces que Emma et vous avez pr&eacute;par&eacute;. Pendant que vous faites le point, vous vous rendez compte qu&rsquo;il manque le formulaire que Emma devait remplir. La fonctionnaire, bien que agac&eacute;e, vous permet de faire cela sur place. Cela prend du temps mais vous y arrivez. </strong></p>\r\n\r\n<p><strong>Il est possible que les personnes atteintes de SPT d&eacute;veloppent des probl&egrave;mes de concentration. Il devient alors plus difficile pour eux de r&eacute;aliser une t&acirc;che du d&eacute;but &agrave; la fin. </strong></p>\r\n\r\n<p>Au bout de 5 minutes de questions, Emma commence &agrave; montrer des signes d&rsquo;impatience et de d&eacute;concentration. Elle met plus de temps &agrave; r&eacute;pondre, et s&rsquo;y reprend &agrave; plusieurs fois pour expliquer sa situation. La fonctionnaire semble perdre patience. Vous d&eacute;cidez alors de...</p>\r\n', 'ressources/26d25ae7e9396d8b9272e515a7b370a7.PNG', 'Etape 7 - b', 'formNOK'),
(53, 12, 24, '<p>Ce ne fut pas toujours facile, mais vous avez r&eacute;ussi &agrave; avoir tout ce qu&rsquo;il vous faut pour partir &agrave; Rio de Janeiro, au Br&eacute;sil. Ce fut une semaine extraordinaire, o&ugrave; Emma et vous avez pu enti&egrave;rement profiter des merveilles du Br&eacute;sil.</p>\r\n\r\n<p><strong>On peut donc voir qu&rsquo;il n&rsquo;est pas &eacute;vident de prendre soin d&rsquo;un proche qui est atteint d&rsquo;un syndrome post-traumatique. Cela implique de prendre des d&eacute;cisions et de trouver un &eacute;quilibre pour &agrave; la fois soutenir mais aussi laisser de la libert&eacute;. Le r&ocirc;le d&rsquo;un aidant n&rsquo;est pas simple et repr&eacute;sente un d&eacute;fi permanent.</strong></p>\r\n', 'ressources/cc2aaddb377018f4f34816ecfd00c707.PNG', 'Fin', NULL),
(54, 12, 24, '<p><strong>Votre insistance &agrave; tout prendre en main a fortement contrari&eacute; Emma qui vous le fait clairement savoir. Elle vous dit que ce n&rsquo;est pas parce qu&rsquo;elle est atteinte d&rsquo;un syndrome qu&rsquo;elle est totalement incapable de prendre sa propre vie en main, et qu&rsquo;elle aimerait pouvoir respirer.</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous disputez sur ce sujet, puis sur d&rsquo;autres et &agrave; force, vous vous rendez compte qu&rsquo;il vaudrait mieux &eacute;viter d&rsquo;aller au Br&eacute;sil dans ces conditions. Vous d&eacute;cidez ensemble de reporter le voyage &agrave; une date ult&eacute;rieure.</p>\r\n', 'ressources/ba0a2dc9571870b990a4474614aff68b.PNG', 'Dommage... Il va falloir rÃ©essayer !', 'score:>7'),
(55, 12, 24, '<p><strong>Emma vous reproche d&rsquo;&ecirc;tre trop dur avec elle et de ne pas prendre en compte ses difficult&eacute;s. M&ecirc;me s&rsquo;il veut pouvoir &ecirc;tre ind&eacute;pendante, elle sait qu&rsquo;elle a besoin de votre aide et souhaite pouvoir compter sur vous quand elle en a besoin&hellip; Ce qui n&rsquo;a pas l&rsquo;air d&rsquo;&ecirc;tre le cas vu votre attitude. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous disputez sur ce sujet, puis sur d&rsquo;autres et &agrave; force, vous vous rendez compte qu&rsquo;il vaudrait mieux &eacute;viter d&rsquo;aller au Br&eacute;sil dans ces conditions. Vous d&eacute;cidez ensemble de reporter le voyage &agrave; une date ult&eacute;rieure.</p>\r\n', 'ressources/2e44b98fb716e19d9eb1f7f8d692fb8b.PNG', 'Dommage... Il va falloir rÃ©essayer !', 'score:<-7'),
(67, 12, 0, '<p>Vous allez jouer &agrave; un jeu sur le mod&egrave;le du jeu dont vous &ecirc;tes le h&eacute;ros. Vous incarnez un proche d&rsquo;une personne en situation de handicap psychique. Dans le handicap psychique, les capacit&eacute;s intellectuelles (raisonnement, calcul etc.) sont indemnes et peuvent &eacute;voluer de mani&egrave;re satisfaisante. C&rsquo;est la possibilit&eacute; de les utiliser qui est d&eacute;ficiente. Les sympt&ocirc;mes sont instables, impr&eacute;visibles. De plus, la personne a du mal &agrave; s&rsquo;int&eacute;grer en soci&eacute;t&eacute; et &agrave; faire face &agrave; des situations variables.</p>\r\n\r\n<p>La personne a n&eacute;anmoins les capacit&eacute;s d&rsquo;effectuer des t&acirc;ches, des activit&eacute;s et de participer &agrave; la vie en soci&eacute;t&eacute;, mais avec des difficult&eacute;s et pourra avoir besoin d&rsquo;une aide.</p>\r\n\r\n<p>Vous allez donc avoir le r&ocirc;le d&rsquo;un proche de la personne. Votre r&ocirc;le est donc d&rsquo;accomplir une t&acirc;che avec elle, tout en r&eacute;agissant aux diff&eacute;rents sympt&ocirc;mes et cons&eacute;quences de son handicap. Il n&rsquo;y a pas de bonnes ou de mauvaises r&eacute;ponses, mais simplement des r&eacute;actions qui peuvent &ecirc;tre adapt&eacute;es ou non &agrave; la situation.</p>\r\n', 'ressources/', 'Avant-Propos', ''),
(68, 12, 21, '<p><strong>Etant donn&eacute; que vous savez les papiers devant vous, vous prenez le relais d&rsquo;Emma pour r&eacute;pondre aux questions qui la concernent. La fonctionnaire semble surprise par votre initiative qui met de c&ocirc;t&eacute; une Emma irrit&eacute;e par votre comportement paternaliste.</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Une fois les questions termin&eacute;es, la fonctionnaire vous dit avec en souriant que c&rsquo;est bon, et que vous recevrez vos passeports sous peu. Vous quittez la mairie, soulag&eacute;s d&rsquo;avoir enfin obtenu ce qu&rsquo;il vous fallait.</p>\r\n', 'ressources/3e7258643790e447940a72b35fe09065.PNG', 'Etape 8 - a', ''),
(69, 12, 22, '<p><strong>Vous expliquez &agrave; la fonctionnaire, qu&rsquo;Emma &agrave; des difficult&eacute;es &agrave; rester attentive &agrave; cause de son trouble psychique. La fonctionnaire comprend et ne pose pas plus de questions sur ce sujet. Emma ne dit plus un mot, elle regarde dans le vide et n&rsquo;intervient plus pendant la proc&eacute;dure, elle est mal &agrave; l&rsquo;aise. Vous terminez donc l&rsquo;entretien. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Une fois les questions termin&eacute;es, la fonctionnaire vous dit avec en souriant que c&rsquo;est bon, et que vous recevrez vos passeports sous peu. Vous quittez la mairie, soulag&eacute;s d&rsquo;avoir enfin obtenu ce qu&rsquo;il vous fallait.</p>\r\n', 'ressources/2d5f8ec589e7a288dccbfde8173f8e2d.PNG', 'Etape 8 - b', ''),
(70, 12, 23, '<p><strong>Emma essaye de reprendre ses esprits suite &agrave; votre r&eacute;action. Elle continue de r&eacute;pondre aux questions mais continue de s&rsquo;embrouiller dans ses propos, au grand dam de la fonctionnaire. L&rsquo;entretien se prolonge plus longtemps que ce que vous aviez pr&eacute;vu. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Une fois les questions termin&eacute;es, la fonctionnaire vous dit avec en souriant que c&rsquo;est bon, et que vous recevrez vos passeports sous peu. Vous quittez la mairie, soulag&eacute;s d&rsquo;avoir enfin obtenu ce qu&rsquo;il vous fallait.</p>\r\n', 'ressources/4456280bf162677f8bc98085e19831bc.PNG', 'Etape 8 - c', ''),
(72, 19, 1, '<p>Diagnostiqu&eacute; schizophr&egrave;ne &agrave; la fin de son adolescence, Marco vit depuis avec sa maladie. Apr&egrave;s des moments difficiles, il a pu &ecirc;tre suivi pour stabiliser sa maladie. Maintenant, gr&acirc;ce &agrave; sa motivation et l&rsquo;aide de ses proches, il tente de reprendre pied et de profiter de sa vie.</p>\r\n\r\n<p>Par exemple, il a d&eacute;cid&eacute; avec son fr&egrave;re Adrien de prendre des cours de th&eacute;&acirc;tre d&rsquo;improvisation dans une troupe de th&eacute;&acirc;tre de sa ville. Il peut voir du monde et prend beaucoup de plaisir &agrave; ces s&eacute;ances.</p>\r\n', 'ressources/3769775bf4a7d31419b21e3e983b401e.PNG', 'Introduction', ''),
(73, 19, 2, '<p>Vous incarnez Adrien, le petit fr&egrave;re de Marco. Cela n&rsquo;a pas toujours facile de vivre avec votre fr&egrave;re, surtout quand vous ne saviez pas ce qu&rsquo;il avait. Depuis que vous et votre famille savent de quoi Marco est atteint, vous pouvez mieux vous organiser. Vous vivez maintenant votre vie, mais vous continuez de voir r&eacute;guli&egrave;rement votre fr&egrave;re.</p>\r\n', 'ressources/889a3d2f8f844945c6edc763294493c3.PNG', 'Etape 1', ''),
(74, 19, 3, '<p><strong>Tous les mardi soir, vous accompagnez votre fr&egrave;re &agrave; une s&eacute;ance de th&eacute;&acirc;tre. Aujourd&rsquo;hui, le cours est d&eacute;cal&eacute; par rapport &agrave; d&#39;habitude. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous d&eacute;sirez connaitre les horaires du bus qui vous emm&egrave;nera &agrave; la salle de th&eacute;&acirc;tre. Vous savez que votre fr&egrave;re &agrave; parfois des difficult&eacute;s &agrave; s&rsquo;organiser dans sa vie de tous les jours. Mais vous d&eacute;sirez tout de m&ecirc;me qu&rsquo;il soit ind&eacute;pendant et qu&rsquo;il g&egrave;re son emploi du temps tout seul.</p>\r\n', 'ressources/2ce00f34a9c81f674b9ceb17d9bb60c7.PNG', 'Etape 2', ''),
(75, 19, 4, '<p><strong>Vous demandez &agrave; Marco s&rsquo;il peut v&eacute;rifier les horaires de bus sur Internet pour &ecirc;tre &agrave; l&rsquo;heure. Marco semble surpris de votre demande, mais se rappelle que le d&eacute;but du cours de th&eacute;&acirc;tre a &eacute;t&eacute; d&eacute;cal&eacute;. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes ont parfois des troubles de la m&eacute;moire qui les font oublier certaines activit&eacute;s du quotidien comme aller &agrave; des rendez-vous. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous demandez s&#39;il va bien se souvenir de la nouvelle horaire de d&eacute;part. Mais il prend l&#39;initiative de partir au bon moment.</p>\r\n', 'ressources/4bd152cbe44bcb45dcc575e2887e56a2.PNG', 'Etape 2 - a', ''),
(76, 19, 5, '<p><strong>Vous dites &agrave; Marco que vous avez regard&eacute; les horaires pour ce soir. Il semble surpris, mais se rappelle que le d&eacute;but du cours de th&eacute;&acirc;tre a &eacute;t&eacute; d&eacute;cal&eacute;. Il fronce les sourcils et n&rsquo;a pas l&rsquo;air d&rsquo;appr&eacute;cier que vous ayez regard&eacute; les horaires &agrave; sa place. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes ont parfois des troubles de la m&eacute;moire qui les font oublier certaines activit&eacute;s du quotidien comme aller &agrave; des rendez-vous. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous demandez s&#39;il va bien se souvenir de la nouvelle horaire de d&eacute;part. Mais il prend l&#39;initiative de partir au bon moment.</p>\r\n', 'ressources/224357bc7c322e865df0012dd56c5302.PNG', 'Etape 2 - b', ''),
(77, 19, 6, '<p><strong>Vous n&rsquo;avez pas demand&eacute; &agrave; Marco de v&eacute;rifier les horaires. Vous le voyez se pr&eacute;parer &agrave; partir vers le th&eacute;&acirc;tre bien plus t&ocirc;t que n&eacute;cessaire. Vous venez le voir pour lui rappeler que la s&eacute;ance a &eacute;t&eacute; d&eacute;cal&eacute;. Il va alors de lui m&ecirc;me v&eacute;rifier les horaires de bus. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes ont parfois des troubles de la m&eacute;moire qui les font oublier certaines activit&eacute;s du quotidien comme aller &agrave; des rendez-vous. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous demandez s&#39;il va bien se souvenir de la nouvelle horaire de d&eacute;part. Mais il prend l&#39;initiative de partir au bon moment.</p>\r\n', 'ressources/d82f21f3f61edf29691fc185bff08902.PNG', 'Etape 2 - c', ''),
(78, 19, 7, '<p><strong>Vous finissez par atteindre l&rsquo;arr&ecirc;t de bus. Apr&egrave;s quelques minutes, le transport vient vous r&eacute;cup&eacute;rer. Vous trouvez des places c&ocirc;te-&agrave;-c&ocirc;te au milieu du bus. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Alors que le d&eacute;but du trajet se d&eacute;roule paisiblement. Marco commence a devenir agit&eacute;. Au bout d&rsquo;un moment, quelque chose le perturbe, et il commence &agrave; regarder bizarrement les autres passagers.</p>\r\n', 'ressources/d9436d08941092d11a4aa00a1d58c13d.PNG', 'Etape 3', ''),
(79, 19, 8, '<p><strong>Marco n&rsquo;a pas l&rsquo;air de comprendre ce que vous lui dites. Il est sur la d&eacute;fensive et a l&rsquo;air traqu&eacute;. Mais petit &agrave; petit, il reprend le contr&ocirc;le et vous remercie de l&rsquo;avoir soutenu. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes peuvent subir des d&eacute;lires hallucinatoires. Lors de ces moments, elles peuvent se sentir pers&eacute;cut&eacute;es et agress&eacute;es par le monde ext&eacute;rieur, et percevoir les autres comme des menaces personnelles. Ils sont alors tr&egrave;s angoiss&eacute;s. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au moment o&ugrave; Marco reprend son calme, vous atteignez votre arr&ecirc;t. Vous sortez alors du bus et rejoignez la salle de th&eacute;&acirc;tre.</p>\r\n', 'ressources/34175d0ad13c4b59dd51a9145acaff25.PNG', 'Etape 3 - a', ''),
(80, 19, 9, '<p><strong>Marco a l&rsquo;air de se sentir agress&eacute; et marmonnent des choses. Les autres passagers du bus le regardent avec m&eacute;fiance. N&eacute;anmoins, la crise finit par passer. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes peuvent subir des d&eacute;lires hallucinatoires. Lors de ces moments, elles peuvent se sentir pers&eacute;cut&eacute;es et agress&eacute;es par le monde ext&eacute;rieur et percevoir les autres comme des menaces personnelles. Ils sont alors tr&egrave;s angoiss&eacute;s. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au moment o&ugrave; Marco reprend son calme, vous atteignez votre arr&ecirc;t. Vous sortez alors du bus et rejoignez la salle de th&eacute;&acirc;tre.</p>\r\n', 'ressources/84ba451889d54dfc150723cef02129fa.PNG', 'Etape 3 - b', ''),
(81, 19, 10, '<p><strong>Marco ne prend pas compte de ce que vous lui dites. Il a l&rsquo;air de lutter pour garder le contr&ocirc;le. Certains passagers vous regardent, vous et votre fr&egrave;re, d&rsquo;un air m&eacute;fiant. Au final, Marco reprend ses esprits, mais a l&rsquo;air &eacute;prouv&eacute;. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes peuvent subir des d&eacute;lires hallucinatoires. Lors de ces moments, elles peuvent se sentir pers&eacute;cut&eacute;es et agress&eacute;es par le monde ext&eacute;rieur et percevoir les autres comme des menaces personnelles. Ils sont alors tr&egrave;s angoiss&eacute;s. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au moment o&ugrave; Marco reprend son calme, vous atteignez votre arr&ecirc;t. Vous sortez alors du bus et rejoignez la salle de th&eacute;&acirc;tre.</p>\r\n', 'ressources/5a52019a36df8cddb62e796ac45cf56e.PNG', 'Etape 3 - c', ''),
(82, 19, 11, '<p><strong>Apr&egrave;s avoir march&eacute; quelques minutes, vous atteignez le th&eacute;&acirc;tre. Plusieurs autres membres du groupe sont d&eacute;j&agrave; arriv&eacute;. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous engagez alors la conversation avec certains d&rsquo;entre eux. Mais Marco reste dans son coin.</p>\r\n', 'ressources/9afd136c234f77466abea0bb4b7dc32d.PNG', 'Etape 4', ''),
(83, 19, 12, '<p><strong>Vous faites signe &agrave; Marco de se joindre &agrave; vous dans votre conversation avec d&rsquo;autres membres. Il s&rsquo;avance vers le groupe l&rsquo;air un peu g&ecirc;n&eacute; et ne place que quelques mots dans la conversation. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes pr&eacute;sentent des difficult&eacute;s sociales. Ils ont du mal &agrave; interagir avec les autres personnes, m&ecirc;me si la maladie est stabilis&eacute;e. Le regard des autres sur leur maladie peut leur peser. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au bout d&rsquo;une dizaine de minutes, l&rsquo;animatrice du th&eacute;&acirc;tre finit par arriver dans la salle pour commencer la s&eacute;ance.</p>\r\n', 'ressources/47df1460ca509035511a47634642bb84.PNG', 'Etape 4 - a', ''),
(84, 19, 13, '<p><strong>Engag&eacute; dans votre conversation, vous ne pr&ecirc;tez pas attention &agrave; Marco, qui reste seul dans son coin. Il attend patiemment le d&eacute;but de la s&eacute;ance sans se pr&eacute;occuper des autres membres de la troupe qui lui jettent par moment des regards h&eacute;sitants. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes pr&eacute;sentent des difficult&eacute;s sociales. Ils ont du mal &agrave; interagir avec les autres personnes, m&ecirc;me si la maladie est stabilis&eacute;e. Le regard des autres sur leur maladie peut leur peser. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Au bout d&rsquo;une dizaine de minutes, l&rsquo;animatrice du th&eacute;&acirc;tre finit par arriver dans la salle pour commencer la s&eacute;ance.</p>\r\n', 'ressources/f3d11e1781b1e3275019c4826024626f.PNG', 'Etape 4 - b', ''),
(85, 19, 14, '<p><strong>Comme d&rsquo;habitude, la s&eacute;ance commence par un &eacute;chauffement. L&rsquo;animatrice explique au groupe les diff&eacute;rents exercices &agrave; r&eacute;aliser en montrant elle-m&ecirc;me l&rsquo;exemple. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Apr&egrave;s vous avoir montr&eacute; quoi faire, chacun commence son &eacute;chauffement. Mais Marco vous regarde l&rsquo;air un peu perdu, comme s&rsquo;il ne savait pas quoi faire. Il conna&icirc;t pourtant les exercices.</p>\r\n', 'ressources/dc3c81ebf5615c644cac147770645f69.PNG', 'Etape 5', ''),
(86, 19, 15, '<p><strong>Vous vous rapprochez de Marco pour lui remontrer l&rsquo;exercice &agrave; r&eacute;aliser en prenant votre temps. Il h&eacute;site au d&eacute;but, mais comprend rapidement la suite d&#39;encha&icirc;nements &agrave; r&eacute;aliser. Il vous explique qu&rsquo;il n&rsquo;avait pas vu le d&eacute;but de l&rsquo;exemple pr&eacute;sent&eacute; par l&rsquo;animatrice et qu&rsquo;il n&rsquo;a pas r&eacute;ussi &agrave; reprendre le fil de l&rsquo;exercice. </strong></p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes ont parfois des difficult&eacute;s &agrave; commencer des actions par elles-m&ecirc;mes. Elles peuvent alors avoir besoin d&rsquo;une aide ext&eacute;rieure pour passer &agrave; l&rsquo;action. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>L&rsquo;&eacute;chauffement prend fin au bout de 5 minutes. L&rsquo;animatrice propose alors de continuer la s&eacute;ance avec une premi&egrave;re improvisation.</p>\r\n', 'ressources/7480ca04b1a4c8d02bb1981d52eb0046.PNG', 'Etape 5 - a', ''),
(87, 19, 16, '<p><strong>Vous continuez votre exercice, Marco arrivera &agrave; se d&eacute;brouiller. Mais rapidement, vous voyez l&rsquo;animatrice se diriger vers Marco qui n&rsquo;arrivait pas &agrave; commencer l&rsquo;exercice. Apr&egrave;s son passage, Marco semble plus s&ucirc;r de ce qu&rsquo;il fait durant l&rsquo;exercice suivant. </strong></p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes ont parfois des difficult&eacute;s &agrave; commencer des actions par elles-m&ecirc;mes. Elles peuvent alors avoir besoin d&rsquo;une aide ext&eacute;rieure pour passer &agrave; l&rsquo;action. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>L&rsquo;&eacute;chauffement prend fin au bout de 5 minutes. L&rsquo;animatrice propose alors de continuer la s&eacute;ance avec une premi&egrave;re improvisation.</p>\r\n', 'ressources/f2fa723cda27cc882f964d37513c4a92.PNG', 'Etape 5 - b', ''),
(88, 19, 17, '<p><strong>Vous vous rapprochez de Marco et lui dites qu&rsquo;il peut y arriver : il l&rsquo;a d&eacute;j&agrave; fait plein de fois ! Apr&egrave;s quelques autres essais rat&eacute;s, Marco arrive finalement &agrave; r&eacute;ussir l&rsquo;encha&icirc;nement, et vous dit qu&rsquo;il n&#39;avait pas r&eacute;ussi &agrave; reprendre le fil de l&rsquo;exercice. </strong></p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes ont parfois des difficult&eacute;s &agrave; commencer des actions par elles-m&ecirc;mes. Elles peuvent alors avoir besoin d&rsquo;une aide ext&eacute;rieure pour passer &agrave; l&rsquo;action.</strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>L&rsquo;&eacute;chauffement prend fin au bout de 5 minutes. L&rsquo;animatrice propose alors de continuer la s&eacute;ance avec une premi&egrave;re improvisation.</p>\r\n', 'ressources/7ca1fba66b80231c8cea1ac5ff98be69.PNG', 'Etape 5 - c', ''),
(89, 19, 18, '<p><strong>L&rsquo;animatrice explique les r&egrave;gles de l&rsquo;improvisation. Par groupes de trois ou quatre, vous devrez improviser une discussion &agrave; propos d&rsquo;un th&egrave;me tir&eacute; au hasard. Vous &ecirc;tes dans le m&ecirc;me groupe que votre fr&egrave;re avec deux autres personnes. Vous obtenez le th&egrave;me : &ldquo;animaux domestiques&rdquo;. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Un des participants d&eacute;marre en se pr&eacute;sentant comme un vendeur d&rsquo;animaux. Vous vous impliquez dans la discussion, tout comme les autres participants. Mais &agrave; chaque fois que c&rsquo;est le tour de Marco, il r&eacute;pond &agrave; peine et ne relance pas la discussion. Les autres participants finissent par ne plus le solliciter.</p>\r\n', 'ressources/5e570a30aadbe3d096a5397386ed0235.PNG', 'Etape 6', ''),
(90, 19, 19, '<p><strong>Malgr&eacute; la pauvret&eacute; des r&eacute;ponses de Marco, vous continuez de le faire participer. Ses relances restent courtes, mais progressent n&eacute;anmoins et sont de plus en plus int&eacute;ressantes. Petit &agrave; petit, les autres participants recommencent &agrave; inclure &agrave; Marco. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes peuvent avoir du mal &agrave; entretenir les conversations. Cela signifie que leur discours peut &ecirc;tre r&eacute;duit, impr&eacute;cis, avec de longs silences ou une prononciation difficile. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Ce jeu continue encore pendant quelques minutes. L&rsquo;animatrice rassemble alors la troupe pour une nouvelle activit&eacute;.</p>\r\n', 'ressources/85b0e8f1f00a0f36a25c660f15a031de.PNG', 'Etape 6 - a', ''),
(91, 19, 20, '<p><strong>Votre groupe de 4 devient effectivement un groupe de 3, et vous &ecirc;tes particuli&egrave;rement inspir&eacute;. Apr&egrave;s un petit moment, Marco va s&rsquo;asseoir un peu &agrave; l&rsquo;&eacute;cart le temps que l&rsquo;exercice se termine. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes peuvent avoir du mal &agrave; entretenir les conversations. Cela signifie que leur discours peut &ecirc;tre r&eacute;duit, impr&eacute;cis, avec de longs silences ou une prononciation difficile. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Ce jeu continue encore pendant quelques minutes. L&rsquo;animatrice rassemble alors la troupe pour une nouvelle activit&eacute;.</p>\r\n', 'ressources/5081570f025db8579179b5ee15f9dfb7.PNG', 'Etape 6 - b', ''),
(92, 19, 21, '<p><strong>Vous &ecirc;tes d&eacute;&ccedil;u des r&eacute;ponses de Marco, vous lui faites remarquer discr&egrave;tement pendant que les autres participants improvisent entre eux. Vous continuez alors l&rsquo;exercice mais vous ne notez pas d&rsquo;am&eacute;lioration de la part de Marco. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes peuvent avoir du mal &agrave; entretenir les conversations. Cela signifie que leur discours peut &ecirc;tre r&eacute;duit, impr&eacute;cis, avec de longs silences ou une prononciation difficile. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Ce jeu continue encore pendant quelques minutes. L&rsquo;animatrice rassemble alors la troupe pour une nouvelle activit&eacute;.</p>\r\n', 'ressources/d78a81515139a9b49d542df9c9dd3d65.PNG', 'Etape 6 - c', ''),
(93, 19, 22, '<p><strong>L&rsquo;animatrice propose un nouvel exercice. Cette fois, les participants passeront par deux chaqu&#39;un leur tour devant les autres. L&rsquo;un des participants doit mimer une &eacute;motion et l&rsquo;autre doit reconna&icirc;tre cette &eacute;motion et la reproduire au plus proche de l&rsquo;identique. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Lorsque vient votre tour avec Marco, vous n&rsquo;avez pas de probl&egrave;me &agrave; l&rsquo;imiter, &agrave; l&rsquo;amusement de tout le monde. Quand c&rsquo;est &agrave; lui de vous imiter, vous d&eacute;cidez de faire la col&egrave;re. Rapidement, un petit blanc s&rsquo;installe. Marco ne semble pas savoir ce que vous faites...</p>\r\n', 'ressources/26b608e71cc5493967741c6a032439bb.PNG', 'Etape 7', ''),
(94, 19, 23, '<p><strong>Vous essayez discr&egrave;tement de dire &agrave; Marco que vous jouez la col&egrave;re. Les autres ne semblent pas vous avoir entendu, mais l&rsquo;animatrice n&rsquo;a pas l&rsquo;air content de ce que vous faites. Marco finit par dire &ldquo;Col&egrave;re&rdquo; mais le ton n&rsquo;est pas vraiment convaincant. </strong></p>\r\n\r\n<p><strong>Les &eacute;motions peuvent affecter diff&eacute;remment les personnes schizophr&egrave;nes. Elles peuvent avoir du mal &agrave; les ressentir, &agrave; les exprimer ou bien avoir des &eacute;motions tout &agrave; fait inappropri&eacute;es &agrave; la situation. Enfin, elles peuvent aussi avoir du mal &agrave; reconna&icirc;tre les &eacute;motions des autres. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous retournez avec les autres et une nouvelle paire prend votre place. Tous les groupes passent, et vient le moment de l&rsquo;exercice final.</p>\r\n', 'ressources/e6d79eb509bdfed4a1f68818fb1b4710.PNG', 'Etape 7 - a', ''),
(95, 19, 24, '<p><strong>Vous exag&eacute;rez les &eacute;motions que vous jouez ce qui provoque l&rsquo;hilarit&eacute; du public. En revanche, Marco &agrave; l&rsquo;air de mieux saisir ce que vous exprimez. Il parvient alors &agrave; imiter quelques unes des &eacute;motions que vous lui avez montr&eacute;. </strong></p>\r\n\r\n<p><strong>Les &eacute;motions peuvent affecter diff&eacute;remment les personnes schizophr&egrave;nes. Elles peuvent avoir du mal &agrave; les ressentir, &agrave; les exprimer ou bien avoir des &eacute;motions tout &agrave; fait inappropri&eacute;es &agrave; la situation. Enfin, elles peuvent aussi avoir du mal &agrave; reconna&icirc;tre les &eacute;motions des autres. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous retournez avec les autres et une nouvelle paire prend votre place. Tous les groupes passent, et vient le moment de l&rsquo;exercice final.</p>\r\n', 'ressources/ebc05ca5959ead6e9ceff751441f0596.PNG', 'Etape 7 - b', ''),
(96, 19, 25, '<p><strong>Un malaise s&rsquo;installe tandis que Marco peine &agrave; trouver et reste perplexe face &agrave; vous. Au moment o&ugrave; vous craignez qu&rsquo;il se d&eacute;courage, il dit &ldquo;De la&hellip; col&egrave;re ?&rdquo; et fait une grimace tr&egrave;s exag&eacute;r&eacute;e de la col&egrave;re. Cela vous fait rire tous les deux et vous reprenez votre place. </strong></p>\r\n\r\n<p><strong>Les &eacute;motions peuvent affecter diff&eacute;remment les personnes schizophr&egrave;nes. Elles peuvent avoir du mal &agrave; les ressentir, &agrave; les exprimer ou bien avoir des &eacute;motions tout &agrave; fait inappropri&eacute;es &agrave; la situation. Enfin, elles peuvent aussi avoir du mal &agrave; reconna&icirc;tre les &eacute;motions des autres. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous retournez avec les autres et une nouvelle paire prend votre place. Tous les groupes passent, et vient le moment de l&rsquo;exercice final.</p>\r\n', 'ressources/138809c3636aabf318f3b962e050a70d.PNG', 'Etape 7 - c', ''),
(97, 19, 26, '<p><strong>Pendant qu&rsquo;elle explique la prochaine improvisation, quelques personnes entrent dans la salle. Il s&rsquo;agit d&rsquo;une autre troupe de th&eacute;&acirc;tre. Ils expliquent qu&rsquo;ils n&rsquo;ont pas re&ccedil;u les nouvelles horaires. L&rsquo;animatrice leur propose de rester et d&rsquo;assister aux prochaines improvisations. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous mettez tous en position pour d&eacute;marrer l&rsquo;improvisation. Mais vous voyez Marco en pleine crise de panique, quitter la sc&egrave;ne et s&rsquo;enfuir derri&egrave;re l&rsquo;estrade. Vous le suivez pour voir ce qui se passe. Il crie qu&rsquo;il a peur de se faire attraper et qu&rsquo;ils sont l&agrave; pour le surveiller.</p>\r\n', 'ressources/8bee8fbdebeb55e7ef04d2fc27fc7376.PNG', 'Etape 8', ''),
(98, 19, 27, '<p><strong>Vous veillez qu&rsquo;il ne se fasse pas mal pendant qu&rsquo;il d&eacute;lire en restant &agrave; l&rsquo;&eacute;cart. Marco met un petit moment pour se calmer. Lorsque l&rsquo;animatrice vient vous rejoindre pour v&eacute;rifier que tout va bien. Vous expliquez que la crise est pass&eacute;e. Vous retournez alors sur sc&egrave;ne avec votre fr&egrave;re pour finir l&rsquo;exercice. </strong></p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes sont vuln&eacute;rables face &agrave; l&rsquo;impr&eacute;vu et pr&eacute;f&egrave;rent les routines. Le changement peut facilement les inqui&eacute;ter et renforcer des sentiments de peur ou cr&eacute;er des d&eacute;lires de pers&eacute;cution. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>La fin de la s&eacute;ance se passe sans encombre, et Marco participe pleinement &agrave; la s&eacute;ance. Des petits signes montrent qu&rsquo;il n&rsquo;est pas enti&egrave;rement rassur&eacute;, mais cela ne l&rsquo;emp&ecirc;che de jouer avec la troupe. La s&eacute;ance se termine et les acteurs se s&eacute;parent.</p>\r\n', 'ressources/02cc302efb417f25f7088e6c8e794843.PNG', 'Etape 8 - a', ''),
(99, 19, 28, '<p><strong>Marco met un petit moment pour retrouver ses esprits. Mais vous le calmez en lui r&eacute;p&eacute;tant qu&rsquo;il est en s&eacute;curit&eacute; et que tout va bien. L&rsquo;animatrice vient vous rejoindre pour v&eacute;rifier que tout va bien. Vous expliquez que la crise est pass&eacute;e. Vous retournez alors sur sc&egrave;ne avec votre fr&egrave;re pour finir l&rsquo;exercice. </strong></p>\r\n\r\n<p><strong>Les personnes schizophr&egrave;nes sont vuln&eacute;rables face &agrave; l&rsquo;impr&eacute;vu et pr&eacute;f&egrave;rent les routines. Le changement peut facilement les inqui&eacute;ter et renforcer des sentiments de peur ou cr&eacute;er des d&eacute;lires de pers&eacute;cution. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>La fin de la s&eacute;ance se passe sans encombre, et Marco participe pleinement &agrave; la s&eacute;ance. Des petits signes montrent qu&rsquo;il n&rsquo;est pas enti&egrave;rement rassur&eacute;, mais cela ne l&rsquo;emp&ecirc;che de jouer avec la troupe. La s&eacute;ance se termine et les acteurs se s&eacute;parent.</p>\r\n', 'ressources/ed837fba5fa2d5e655b227abbbb1af78.PNG', 'Etape 8 - b', ''),
(100, 19, 29, '<p>Marco vous dit qu&rsquo;il a vraiment appr&eacute;ci&eacute; la s&eacute;ance. Le th&eacute;&acirc;tre en g&eacute;n&eacute;ral semble vraiment l&rsquo;aider &agrave; s&rsquo;ouvrir et &agrave; combattre la schizophr&eacute;nie. Entre cela et ses rendez-vous avec un psychiatre, Marco souffre de moins en moins de sa maladie.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>On peut donc voir qu&rsquo;il n&rsquo;est pas &eacute;vident de prendre soin d&rsquo;un proche qui est atteint de schizophr&eacute;nie. Cela implique de prendre des d&eacute;cisions et de trouver un &eacute;quilibre pour &agrave; la fois soutenir mais aussi laisser de la libert&eacute;. Le r&ocirc;le d&rsquo;un aidant n&rsquo;est pas simple et repr&eacute;sente un d&eacute;fi permanent.</strong></p>\r\n', 'ressources/1d1cc5efb7814603c86b8aa740d74335.PNG', 'Fin', ''),
(101, 19, 29, '<p><strong>Votre insistance &agrave; tout prendre en main a fortement contrari&eacute; Marco qui vous le fait clairement savoir. Il vous dit que ce n&rsquo;est pas parce qu&rsquo;il est atteint de schizophr&eacute;nie qu&rsquo;il est totalement incapable de prendre sa propre vie en main, et qu&rsquo;il aimerait pouvoir respirer. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous disputez sur ce sujet. Marco refuse d&rsquo;aller &agrave; d&rsquo;autres s&eacute;ances de th&eacute;&acirc;tre avec vous tant que vous aurez ce comportement avec lui qui l&rsquo;emp&ecirc;che de profiter du th&eacute;&acirc;tre.</p>\r\n', 'ressources/f4723ab3fc94bb7cf2679b88368ecef0.PNG', 'Dommage... Il va falloir rÃ©essayer !', 'score:>7'),
(102, 19, 29, '<p><strong>Marco vous reproche d&rsquo;&ecirc;tre trop dur avec lui et de ne pas prendre en compte ses difficult&eacute;s. M&ecirc;me s&rsquo;il veut pouvoir &ecirc;tre ind&eacute;pendant, il sait qu&rsquo;il a besoin de votre aide et souhaite pouvoir compter sur vous quand il en a besoin&hellip; Ce qui n&rsquo;a pas l&rsquo;air d&rsquo;&ecirc;tre le cas vu votre attitude. </strong></p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Vous vous disputez sur ce sujet. Marco refuse d&rsquo;aller &agrave; d&rsquo;autres s&eacute;ances de th&eacute;&acirc;tre avec vous tant que vous aurez ce comportement avec lui qui l&rsquo;emp&ecirc;che de profiter du th&eacute;&acirc;tre.</p>\r\n', 'ressources/ad8f2e2653e03687f3943db6cc296dbf.PNG', 'Dommage... Il va falloir rÃ©essayer !', 'score:<-7');

-- --------------------------------------------------------

--
-- Structure de la table `scenario`
--

CREATE TABLE `scenario` (
  `id_scenario` int(11) NOT NULL,
  `nom` varchar(500) CHARACTER SET utf8 NOT NULL,
  `resume` varchar(5000) CHARACTER SET utf8 DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Contenu de la table `scenario`
--

INSERT INTO `scenario` (`id_scenario`, `nom`, `resume`) VALUES
(12, 'Stress Post Traumatique - DÃ©marches administratives', 'Vous allez jouer Ã  un jeu sur le modÃ¨le du jeu dont vous Ãªtes le hÃ©ros. Vous incarnez un proche dâ€™une personne en situation de handicap psychique. Dans le handicap psychique, les capacitÃ©s intellectuelles (raisonnement, calcul etc.) sont indemnes et peuvent Ã©voluer de maniÃ¨re satisfaisante. Câ€™est la possibilitÃ© de les utiliser qui est dÃ©ficiente. Les symptÃ´mes sont instables, imprÃ©visibles. De plus, la personne a du mal Ã  sâ€™intÃ©grer en sociÃ©tÃ© et Ã  faire face Ã  des situations variables. \r\nLa personne a nÃ©anmoins les capacitÃ©s dâ€™effectuer des tÃ¢ches, des activitÃ©s et de participer Ã  la vie en sociÃ©tÃ©, mais avec des difficultÃ©s et pourra avoir besoin dâ€™une aide.\r\nVous allez donc avoir le rÃ´le dâ€™un proche de la personne. Votre rÃ´le est donc dâ€™accomplir une tÃ¢che avec elle, tout en rÃ©agissant aux diffÃ©rents symptÃ´mes et consÃ©quences de son handicap. Il nâ€™y a pas de bonnes ou de mauvaises rÃ©ponses, mais simplement des rÃ©actions qui peuvent Ãªtre adaptÃ©es ou non Ã  la situation.'),
(19, 'SchizophrÃ©nie - Cours de ThÃ©Ã¢tre', '');

--
-- Index pour les tables exportées
--

--
-- Index pour la table `bouton`
--
ALTER TABLE `bouton`
  ADD PRIMARY KEY (`id_bouton`);

--
-- Index pour la table `page`
--
ALTER TABLE `page`
  ADD PRIMARY KEY (`id_page`);

--
-- Index pour la table `scenario`
--
ALTER TABLE `scenario`
  ADD PRIMARY KEY (`id_scenario`);

--
-- AUTO_INCREMENT pour les tables exportées
--

--
-- AUTO_INCREMENT pour la table `bouton`
--
ALTER TABLE `bouton`
  MODIFY `id_bouton` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=145;
--
-- AUTO_INCREMENT pour la table `page`
--
ALTER TABLE `page`
  MODIFY `id_page` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=104;
--
-- AUTO_INCREMENT pour la table `scenario`
--
ALTER TABLE `scenario`
  MODIFY `id_scenario` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=24;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
